### ISSUE TITLE
Abweichende Zahlen für Niedersachsen

### ISSUE THREAD

**Issue by errotu** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#1]
Vielen Dank für diesen Service! Wir nutzen das Angebot im [D64 Covidbot](https://github.com/eknoes/covidbot/).

Mir ist ein (möglicher) Fehler aufgefallen: Für Niedersachsen wird hier im Datensatz (und [im Dashboard](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/COVID-19-Trends/COVID-19-Trends.html?__blob=publicationFile#/home)) eine Hospitalisierungsinzidenz von 1,39 ausgegeben. Das Land Niedersachsen [meldet dagegen 2,8](https://www.niedersachsen.de/Coronavirus/aktuelle_lage_in_niedersachsen/niedersachsen-und-corona-aktuelle-leitindikatoren-203487.html). Wie kommt es zu dieser Differenz?

**Comment by HannesWuensche** [comment]
Hallo @errotu,

die Hospitalisierungsinzidenz des RKIs basiert auf dem Meldesystem nach IfSG, bei dem die Gesundheitsämter laborbestätigte Fälle melden. Dabei kann es zu größeren Nachmeldungen kommen. Das Land Niedersachsen verwendet in seinem Dashboard Daten des IVENA Systems, bei dem die Krankenhäuser einen aggregierten Wert der Hospitalisierungsfälle direkt übermitteln. Dieser Wert ist weniger von Nachmeldungen betroffen. 
Da die IVENA Daten eine eigene Erhebung darstellen, sind sie nicht mit den laborbestätigten Fällen verknüpfbar. In Folge können keine weiterführenden Stratifizierungen oder Analysen (z.b. nach Alter oder Impfstatus) durchgeführt werden. Das RKI verwendet daher die Daten des Meldesystems nach IfSG. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by errotu** [comment]
Danke für die Auskunft!
