### ISSUE TITLE
Unklarheiten bei den adjustierten Daten

### ISSUE THREAD

**Issue by torstenwerner** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#10]
In der Tabelle unter https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#variablenauspr%C3%A4gungen-1 wird nach der Spalte Bundesland_Id eine Spalte Bevoelkerung angegeben. In den Daten gibt es diese Spalte nicht.

Es wäre schön, wenn sie in der Tabelle die Spalten laufend von 1...n durchnummerieren könnten.

Die Daten aktuell ab Zeile 4553
https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/blob/master/Aktuell_Deutschland_adjustierte-COVID-19-Hospitalisierungen.csv#L4553 sehen ungültig aus. Könnten Sie diese bitte kurz erläutern?

**Comment by torstenwerner** [comment]
Hallo Herr Wünsche (@HannesWuensche), vielen Dank! Der Vorteil für mich wäre, dass ich nicht selbst durchzählen müsste, welche Spalten ich im Chart anzeigen möchte. Ich bereite auch gern einen Merge Request vor, wenn Sie sich vorstellen können, dass er akzeptiert wird.

**Comment by HannesWuensche** [comment]
Hallo @torstenwerner,

Meinen sie eine Nummerierung in der Dokumentation oder den Daten selbst? 
In der Dokumentation können wir ohne Probleme die Zeilen nummerieren. 

Was die Daten selbst betrifft, hier sehe ich leider keine Chance für eine Nummerierung. Unsere nächsten Entwicklungsschritte werden eher in die Richtung gehen, dass wir eine standardisiertes Vokabular/Ontologie für die Variablen verwenden werden.
Ziel ist es die Maschinenlesbarkeit und Interoperabilität zu erhöhen.

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by torstenwerner** [comment]
Hallo @HannesWuensche , ich meine nur die Tabelle(n) im README. Dort wäre eine laufende Nummer für die darin beschriebenen Datenspalten schön.
