### ISSUE TITLE
Adjustierte Daten fehlen im Archiv-Ordner

### ISSUE THREAD

**Issue by dwolffram** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#11]
Hallo, leider fehlt heute die Datei `2021-12-15_Deutschland_adjustierte-COVID-19-Hospitalisierungen.csv` im Archiv-Ordner. Könnten Sie diese bitte noch ergänzen? Das wäre super, danke!

**Comment by HannesWuensche** [comment]
Hallo @dwolffram,

vielen Dank für den Hinweis. Die Daten sind jetzt online. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by dwolffram** [comment]
Perfekt, vielen Dank fürs Ergänzen!
