### ISSUE TITLE
Rohdaten vom 16.12. fehlen 

### ISSUE THREAD

**Issue by jbracher** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#14]
Guten Morgen, heute wurden nur die adjustierten Daten hochgeladen. Könnten die rohen Daten noch ergänzt werden? Vielen Dank!

**Comment by HannesWuensche** [comment]
Hallo @jbracher,

vielen Dank für den Hinweis. Die Daten sind jetzt online. 
Der Fehler ist schon einige Male aufgetreten.  Wir sind derzeit an der Überarbeitung unserer Skripte um die Bereitstellung noch verlässlicher zu gestalten. 

Mit besten Grüßen
Hannes Wünsche
für das Team RKI | Open Data
