### ISSUE TITLE
2022-01-17_Deutschland_COVID-19-Hospitalisierungen.csv fehlt im Archiv

### ISSUE THREAD

**Issue by jbracher** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#15]
Die Datei mit den unkorrigierten Werten war heute nur im Hauptordner verfügbar, es wäre schön, wenn sie auch im Archiv ergänzt würde. Danke!

**Comment by HannesWuensche** [comment]
Hallo @jbracher,

nochmals Danke für den Hinweis. 
Wir haben heute einen Bug-fix umgesetzt und hoffen, dass ab morgen die Daten aktuell und stabil bereitgestellt werden. 

Mit besten Grüßen
Hannes Wünsche
für das Team RKI | Open Data
