### ISSUE TITLE
Heutiges Update fehlt

### ISSUE THREAD

**Issue by jbracher** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#16]
Liebes RKI-Team,

heute sind keine neuen Daten für die Hospitalisierungsinzidenzen online gegangen - werden diese heute noch erscheinen?

Danke für eine kurze Rückmeldung und beste Grüße, Johannes

**Comment by anderHeidenM** [comment]
Hallo Johannes,

gestern gab es eine Umstellung der Datenbank - wir sind aber dabei die Analysen durchzuführen und innerhalb der nächsten Stunden sollten auch die Hospitalisierungen auf GitHub sein!

Viele Grüße
Matthias

-----Ursprüngliche Nachricht-----
Von: Johannes Bracher ***@***.***> 
Gesendet: Donnerstag, 14. Juli 2022 12:33
An: robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland] Heutiges Update fehlt (Issue #16)

Liebes RKI-Team,

heute sind keine neuen Daten für die Hospitalisierungsinzidenzen online gegangen - werden diese heute noch erscheinen?

Danke für eine kurze Rückmeldung und beste Grüße, Johannes

**Comment by jbracher** [comment]
Danke für die schnelle Antwort! Dann halten wir die Augen offen.

**Comment by jwildeboer** [comment]
Danke für das Update - aber da sind jetzt nur die Bundesländer 1-8 enthalten? Zumindest in https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/blob/master/Aktuell_Deutschland_adjustierte-COVID-19-Hospitalisierungen.csv :(

**Comment by goerlich-bz** [comment]
Liebes RKI-Team,

vielen Dank für die schnellen Reaktionen. In der adjustierten Hospi reicht Baden-Württemberg jedoch nur bis zum 22.5.22 zurück - ah und wie bereits entdeckt fehlen die folgenden Bundesländer sogar ganz, es bricht an der Stelle einfach ab.

**Comment by jwildeboer** [comment]
Werden die fehlenden Zahlen in der adjustierten Hospitalisierung morgen ergänzt? Ein Tag mit fehlenden Zahlen, OK. Unfein ist es trotzdem :(

**Comment by HannesWuensche** [comment]
Hallo @jbracher, @jwildeboer und @goerlich-bz 

die Umstellung der Datenbank hat leider mehr Komplikationen nach sich gezogen als gehofft. Wir haben im Archiv die vollständigen Daten für den 2022-07-14 ergänzt. Heute morgen sollte alles wieder reguläre veröffentlicht worden sein. 
Vielen Dank für die Rückmeldungen!

Mit besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data
