### ISSUE TITLE
Verständnisfrage zur Updatefrequenz

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#17]
In dem Update vom 2022-07-17 waren für Bayern (zumindest, andere BL habe ich nicht geprüft) keine neuen Zahlen gegenüber dem Vortag enthalten.

Heute gab es (noch?) kein Update.

Ist das die normale Updatefrequenz? Also Di-Sa täglich mit neuen Zahlen, Sonntag und Montag keine neuen Zahlen, bzw. kein Update?

Jan

**Comment by RKIOpenData** [comment]
Hallo @jwildeboer,

vielen Dank für die Info. Es gab in den letzten beiden Tagen leider Probleme beim automatisierten Upload. Deshalb kamen die Daten später als sonst. Jetzt sind die aktuellen Daten aber comitted. Im Normalfall werden die Daten jeden Tag aktualisiert.

Mit besten Grüßen
Knut Perseke
für das Team RKI | Open Data

**Comment by jwildeboer** [comment]
In der Tabelle "adjustiert" ist (zumindest) für Bayern aber leider immer noch am 16.07. Schluss :(
<img width="750" alt="Screenshot 2022-07-18 at 13 43 05" src="https://user-images.githubusercontent.com/873028/179504277-1801247a-e0bb-4cb6-ae4d-7a7526064d7b.png">
