### ISSUE TITLE
2022-11-06 - kein Update?

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#19]
Normalerweise wird ja bis ca 10 Uhr alles aktualisiert. Heute aber nicht. Kleines Oopsie oder wird die Updatefrequenz geändert?

Jan

**Comment by RKIOpenData** [comment]
Hallo @jwildeboer,

vielen Dank für den Hinweis. Ja, da gab es ein Problem auf unserer Seite. Die Daten sind jetzt aktualisiert. Falls es noch Probleme gibt, gern das Issue nochmal öffnen

Mit besten Grüßen
Knut Perseke
für das Team RKI | Open Data
