### ISSUE TITLE
Bitte Daten auf Kreisebene bereitstellen

### ISSUE THREAD

**Issue by rdlarah** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#2]
Hallo zusammen,

da in einigen Bundesländern, z. B. in MV, Rechtsfolgen an die sogenannte Hospitalisierungsinzidenz auf Kreisebene geknüpft sind, etwa Einstufung nach Stufenplänen, ist es m. E. zwingend, daß die entsprechenden Daten nicht nur aggregiert auf Bundes- bzw. BL-Ebene zur Verfügung gestellt werden sondern wie die Infektionszahlen auch detaillierter auf Ebene der Landreise, kreisfreien Städte bzw. in Berlin der Bezirke.

Danke und Gruß
Harald

**Comment by HannesWuensche** [comment]
Hallo rdlarah,

vielen Dank für die Anfrage und den Hinweis.
 
Im Infektionsschutz-Gesetzt ist geregelt, dass das Robert Koch-Institut, Daten zur Hospitalisierung von COVID-19 Patient:innen nur auf Ebene der Bundesländer berichten muss.  Den Bundesländern ist es jedoch möglich, Daten auch auf Kreisebene zu veröffentlichen. 
Da die von ihnen angesprochenen Reglungen in jedem Bundesland verschieden sind und bei der Interpretation der Hospitalisierungsdaten auf Kreisebene viele lokale Kontextinformationen nötig sind, wird das RKI vorerst keine Daten auf Kreisebene zur Verfügung stellen. Diesbezüglich müssen wir sie leider an die Landesstellen verweisen. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
