### ISSUE TITLE
Unvollständige Anzeige der Archivdaten

### ISSUE THREAD

**Issue by 4nnabeh** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#21]
Moin, uns ist aufgefallen, dass in diesem Ordner offenbar keine neuen Dateien mehr geschrieben werden https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/tree/master/Archiv, da er zu voll wurde. Die neueste Datei ist vom 14.12. Da wir die Daten noch auf NDR.de benutzen, wären wir dankbar, wenn das Problem zeitnah behoben werden könnte. Beste Grüße und einen guten Rutsch!

**Comment by HannesWuensche** [comment]
Hallo @4nnabeh,

könntest du den Fehler etwas genauer erläutern? 
Github kann nur 1000 Elemete pro Ordner anzeigen. Bei uns sehen wir diesbezüglich einen Hinweis:
```
Sorry, we had to truncate this directory to 1,000 files. 32 entries were omitted from the list. 
```
Unter den absoluten Pfaden, sind die Dateien auch erreichbar: [2022-12-29_Deutschland_COVID-19-Hospitalisierungen.csv](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/blob/master/Archiv/2022-12-29_Deutschland_COVID-19-Hospitalisierungen.csv)
Bei eine pull/clone sollten auch alle Dateien vorhanden sein? 

Beste Grüße und einen guten Start ins Neue Jahr
@HannesWuensche 
für das Team RKI | Open Data

**Comment by 4nnabeh** [comment]
Danke für die prompte Antwort @HannesWuensche und sorry fürs Aufschrecken zwischen den Jahren. Ich habe jetzt verstanden, dass das Problem bei den Daten des von uns verwendeten Nowcasts (aus historischen Gründen nicht der RKI-Nowcast) liegt und nicht bei denen, die wir von Euch ziehen. Ebenfalls einen guten Start ins Neue Jahr!
