### ISSUE TITLE
Seit 3 Tagen kein Update

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#23]
Laut readme.md : "Die Daten werden täglich vollständig neu erzeugt, dieser Datenstand ersetzt den Datenstand des Vortages." aber seit 3 Tagen kein Update mehr. Wird dieser Datensatz nicht gepflegt oder wurde die Aktualisierung eingestellt?

**Comment by jbracher** [comment]
Guten Morgen, uns ist auch gerade aufgefallen, dass die Daten über das Wochenende nicht aktualisiert wurden. Es wäre super, wenn die Dateien vom Samstag und Sonntag auch noch nachträglich mit eingestellt werden könnten. Vielen Dank!

**Comment by jwildeboer** [comment]
Leider auch heute kein Update von RKI Seite. Weder im Repository, noch hier im Issue. Schade. Hoffen wir, daß morgen entweder neue Zahlen oder eine Erklärung (oder beides :) kommt.

**Comment by HannesWuensche** [comment]
Liebe User,

leider kam es am Wochenende zu einer Unterbrechung der Datenbereitstellung.
Die aktuellen Daten sowie das Archiv sind soeben bereitgestellt worden.

Mit Besten Grüßen
@HannesWuensche 
für das Team RKI | Open Data

**Comment by jbracher** [comment]
Vielen Dank!

**Comment by jwildeboer** [comment]
Erleichterung :)

**Comment by jwildeboer** [comment]
Es fehlen immer noch die Daten vom Wochenende. Hoffentlich morgen gefixt.

**Comment by HannesWuensche** [comment]
Hallo @jwildeboer,

Danke für den Hinweis. Da scheint es einen Fehler zu geben. Ich habe die Aktualisierung für morgen früh ausgesetzt und schau mir das mit meinen Kolleg:innen an.

Beste Grüße
@HannesWuensche

**Comment by jwildeboer** [comment]
Habe das nochmal etwas detaillierter in https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/issues/24 beschrieben.
