### ISSUE TITLE
Diskrepanz in den Zahlen -2023-05-10

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#24]
Die Datei https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/blob/master/Aktuell_Deutschland_COVID-19-Hospitalisierungen.csv lässt sich ja nach Bundesland und dann nach Altersgruppe sortieren. Wenn ich das für Bayern mache und nur die Altersgruppe "0" nehme um die Gesamtzahlen zu sehen, dann kommt das hier heraus:

<img width="875" alt="Screenshot 2023-05-10 at 08 38 20" src="https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/assets/873028/84b66656-cca3-4a55-ba43-3bc6ad68e2e0">

Mein Problem ist jetzt - was ist das für eine Zahl? Tagesmeldung? Um Nachmeldungen korrigiert? Daher vergleiche ich mit https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/blob/master/Aktuell_Deutschland_adjustierte-COVID-19-Hospitalisierungen.csv und stelle fest: die Zahlen aus der ersten Datei finden sich nicht zurück in der zweiten Datei. Weder als fixiert, aktualisiert oder PS adjustiert.

Zusätzlich stelle ich fest: die zweite Datei mit dem Nowcast hat nur Zahlen bis 2023-05-06. Auch die aktuellste Datei von heute wieder:

<img width="1128" alt="Screenshot 2023-05-10 at 08 39 07" src="https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/assets/873028/b1a9bcdd-e2ae-4f48-bf9e-19a38fc9fcf3">

Daher zweiteilige Frage: Warum die Diskrepanz und warum fehlen die letzten 4 Tage in der adjustierten Datei?

**Comment by jwildeboer** [comment]
Heute scheinen die Zahlen wieder so wie früher zu sein. Vielen Dank für den Fix!

**Comment by jwildeboer** [comment]
Safe to close, @HannesWuensche ?

**Comment by HannesWuensche** [comment]
Hallo @jwildeboer,

vielen Dank für den Hinweis zu der Unstimmigkeit in den Daten. Durch die Probleme am Wochenende hatte sich ein Fehler eingeschlichen der zur Abweichung zwischen den beide Datei geführt hatte. 

>Mein Problem ist jetzt - was ist das für eine Zahl? Tagesmeldung? Um Nachmeldungen korrigiert?

Um noch kurz auf die Fragen einzugehen möchte ich auf folgenden Abschnitt der [Dokumentation](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#hospitalisierte-covid-19-f%C3%A4lle-nach-bundesland-und-altersgruppe) verweisen: 

>Die Hospitalisierungsdaten bilden einen tagesaktuellen Stand (00:00 Uhr) aller über das Meldesystem gemäß Infektionsschutzgesetz an das RKI übermittelten COVID-19-Fälle, bei denen eine Hospitalisierung angegeben ist, ab. Das bedeutet, dass alle, bis 00:00 Uhr des Tages JJJJ-MM-TT, von den Gesundheitsämtern über die zuständigen Landesbehörden an das RKI übermittelten Hospitalisierungen mit Bezug zu COVID-19 im Datenstand enthalten sind. Die Daten werden täglich vollständig neu erzeugt, dieser Datenstand ersetzt den Datenstand des Vortages.

Da heißt in der Datei ist immer der aktuellste Datenstand inklusive aller Nachmeldungen und Korrekturen enthalten.

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data
