### ISSUE TITLE
Fehlende Archiv-Dateien (20.05. und 21.05.)

### ISSUE THREAD

**Issue by dwolffram** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#26]
Hallo, wäre es eventuell möglich, die fehlenden Archiv-Dateien vom 20.05. und 21.05. noch zu ergänzen?
Das wäre sehr hilfreich für unser Projekt, danke!

**Comment by jbracher** [comment]
Guten Morgen @HannesWuensche, wäre es möglich, diese fehlenden Daten noch zu ergänzen? Auf https://covid19nowcasthub.de/ laufen leider ohne diese Daten viele automatisierte Prozesse ins Leere. Vielen Dank im Voraus!
