### ISSUE TITLE
Einfachere URL

### ISSUE THREAD

**Issue by meiers** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#3]
Super Dashboard!
Aber macht es doch unter einer einfachen URL erreichbar, z.B. `rki.de/covid19trends` oder als Subdomain (ähnlich zu dem bisherigen Dashboard, `corona.rki.de`)

Edit
Gemeint ist dieses Dashboard: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/COVID-19-Trends/COVID-19-Trends.html?__blob=publicationFile#/home

**Comment by HannesWuensche** [comment]
Hallo @meiers,

Danke für das positive Feedback! 

Das Dashboard ist unter folgender URL aufrufbar: https://rki.de/covid-19-trends
In der Dokumentation zu finden unter: [Weiter Veröffentlichung der Daten](https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#weitere-ver%C3%B6ffentlichung-der-daten)

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
