### ISSUE TITLE
Tabelle adjustierte Daten geht nur bis 2023-07-15

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#30]
In der adjustierten Tabelle fehlen auch heute die Daten zwischen 2023-07-15 und heute.

Jan

**Comment by RKIOpenData** [comment]
Hallo Jan,

wir hatten ein paar Probleme bei der Bereitstellung der adjustierten Daten. Mit dem heutigen Upload sind die Daten wieder aktuell.

viele Grüße
Knut Perseke
für das RKI Open Data Team
