### ISSUE TITLE
2023-07-22 Wieder keine Updates

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#32]
Scheint ja doch ein persistentes Problem zu sein :( Ich schätze bis Montag wird es wohl keine Aktualisierung geben. Wie auch schon letztes Wochenende. Schade! Hoffentlich findet sich bald eine echte Lösung!

Jan

**Comment by RKIOpenData** [comment]
Hallo Jan,

ja, leider gibt es aktuell öfter Probleme mit den adjustierten Daten. Wir arbeiten an einer Lösung.

Die Daten sind jetzt erstmal wieder aktuell, deshalb schließe ich das Issue erstmal wieder.

viele Grüße
Knut Perseke
für das Team RKIOpenData
