### ISSUE TITLE
Einstellung der adjustierten Hospitalisierungen

### ISSUE THREAD

**Issue by RKIOpenData** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#35]
Liebe User,
	
durch die aktuell im Vergleich geringeren Hospitalisierungszahlen ist eine Adjustierung dieser Zahlen nicht verlässlich möglich. Deshalb wird die Adjustierung der Hospitalisierungen bis auf Weiteres eingestellt und auch die Ergebnisse nicht mehr über GitHub zur Verfügung gestellt. Die alten adjustierten Zahlen sind weiterhin über das Archiv abrufbar.
	
Die aktuellen (nicht adjustierten) Hospitalisierungszahlen werden weiterhin zur Verfügung stehen.
	
	
Mit besten Grüßen
Knut Perseke
für das Team | RKI Open Data

**Comment by jwildeboer** [comment]
Vielen Dank für den Hinweis! In der verbleibenden Tabelle werden aber weiterhin die um Nachmeldungen korrigierten Hospitalisierenden erfasst, korrekt?

Jan

**Comment by RKIOpenData** [comment]
Hi Jan,

ja genau. Für die verbleibende Hospitalisierungsdatei bleibt alles wie gehabt, auch mit den Anpassungen für die Nachmeldungen.

mit besten Grüßen
Knut Perseke
für das Team | RKI Open Data

**Comment by HannesWuensche** [comment]
Liebe Alle, 

durch die derzeit ansteigenden Fallzahlen, ist es aus fachlicher Sicht sinnvoll die Bereitstellung der adjustierten Hospitalisierungsinzidenzen wieder aufzunehmen. 

Die Datei `Aktuell_Deutschland_adjustierte-COVID-19-Hospitalisierungen.csv` wird ab sofort wieder täglich bereitgestellt. 

Mit besten Grüßen
@HannesWuensche 
Für das Team RKI | Open Data
