### ISSUE TITLE
Aktuell_Deutschland_adjustierte-COVID-19-Hospitalisierungen.csv

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#36]
Hi,

Die adjustierten Daten wurden zuletzt am 2023-08-14 aktualisiert.

Hängt da was in einer Pipeline oder kommt das nächste Update nur später durch Urlaub/Krankheit?

Viele Grüsse
David

**Comment by HannesWuensche** [comment]
Hallo @icestorm972 

siehe #35.

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data
