### ISSUE TITLE
Problem in der Datenbereistllung 2023-08-25

### ISSUE THREAD

**Issue by HannesWuensche** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#37]
Liebe User,

heute gibt es leider ein Problem mit den SurvNet Daten. Wir arbeiten an einer Lösung. 
Siehe: https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland/issues/8

Mit Besten Grüßen
@HannesWuensche 
für as Team RKI | Open Data

**Comment by jwildeboer** [comment]
Seit 4 Tagen mittlerweile keine Aktualisierung der Daten. Gibt es eine Stellungnahme dazu seitens RKI? Und auch eine Aussage ab wann es wieder Daten gibt?

**Comment by jbracher** [comment]
Lieber Herr Wünsche, werden die fehlenden Daten der letzten Tage noch nachträglich zur Verfügung gestellt werden? Das wäre für unser Projekt https://covid19nowcasthub.de/ sehr hilfreich (dort sind wir darauf angewiesen, für jeden Tag eine Datenversion zu haben).

**Comment by RKIOpenData** [comment]
Liebe User,

die aktuellen Daten sind jetzt wieder verfügbar. Wir klären grade noch ob und wie wir die historischen Daten nachliefern können.

beste Grüße
Knut Perseke
für das Team | RKI Open Data

**Comment by RKIOpenData** [comment]
Liebe User, lieber @jbracher 

wir haben jetzt auch die historischen Daten noch einmal hochgeladen.  Wenn noch etwas fehlen sollte gebt gern noch einmal Feedback.

beste Grüße
Knut Perseke
für das Team | RKI Open Data
