### ISSUE TITLE
Bundesweit: Fehlende Tagesmeldungen 25.-28. August 

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#38]
Die korrigierten Zahlen sind da, aber die Tagesmeldungen für den 25.-28. August stehen immer noch auf 0. (Adjustierte Tabelle, Spalte fixierte_7T_Hospitalisierung_Faelle).
<img width="885" alt="Screenshot 2023-09-01 at 20 41 28" src="https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/assets/873028/75bf6acb-a784-4a4f-a025-2dcc20767a83">

**Comment by RKIOpenData** [comment]
Hallo Jan,

vielen Dank für dein Feedback. Die Einträge zwischen dem 25. und 28.08. sind tatsächlich fachlich korrekt, da an diesen Tagen aufgrund technischer Probleme bei der Meldesoftware keine COVID-19 Hospitalisierungen am RKI empfangen wurden.

beste Grüße
Knut Perseke
für das Team RKI | Open Data

**Comment by jwildeboer** [comment]
Hm. Schade. Dann bleibt es halt bei der Lücke in den Zahlen.
