### ISSUE TITLE
Unterschied zu offiziellen RKI Zahlen?

### ISSUE THREAD

**Issue by Kexplx** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#4]
Hi,

in [diesem](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/COVID-19-Trends/COVID-19-Trends.html?__blob=publicationFile#/home) RKI dashboard und in anderen [Medienberichten](https://www.tagesschau.de/inland/rki-zahlen-861.html) werden unterschiedliche Werte für die 7-Tage-Hospitalisierung genannt als in eurer [csv datei](https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/master/Aktuell_Deutschland_COVID-19-Hospitalisierungen.csv).

Dashboard |  Eure CSV Datei
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/29175032/142717221-6ab652f6-09bc-43df-93e0-b8306f2d7495.png)  |  ![image](https://user-images.githubusercontent.com/29175032/142717511-33b581d9-b12f-4735-a8ac-cd5e9a9d2050.png)

Woran liegt das, und wie komme ich von dem "00+" Wert in eurer Tabelle auf den offiziellen RKI Wert (z.B. für Bayern)?

Trotzdem danke für die tolle Arbeit in diesem Repo 👏

**Comment by pitrade** [comment]
Das liegt am Meldeverzug. Der Screenshot "Dashboard" zeigt den Wert für den 19.11.2021 aus der Meldung (CSV-Datei) vom 19.11.2021. Im Screenshot "Eure CSV Datei" ist es der Wert für den 19.11.2021 aus der Meldung vom 20.11.2021. Dieser enthält zusätzlich die Hospitalisierungen, die am 20.11.2021 dem RKI vorlagen, jedoch noch nicht am 19.11.2021. Mit der Zeit wird der Wert für den 19.11.2021 weiter steigen, weil für diesen Tag Hospitalisierungen nachgemeldet werden. Heute beträgt der Wert für den 19.11.2021 bereits 6.62, langfristig wird er um 11 liegen.
<img width="348" alt="Bildschirmfoto 2021-11-21 um 04 40 22" src="https://user-images.githubusercontent.com/13933402/142748616-844b1fc9-4b3a-4869-a82b-ee967cc0d570.png">
.

**Comment by Kexplx** [comment]
i see, danke @pitrade

**Comment by pitrade** [comment]
Sie werden rückwirkend aktualisiert, aber das ist Teil des Problems. Der Wert in der Grafik von vor einer Woche enthält zusätzlich zum initialen Wert die Nachmeldungen von 7 weiteren Tagen und ist deshalb in der Grafik höher als alle neueren Werte. 
Die 6.62 vom 19.11.2021 werden morgen ca. 7.1, in einer Woche ca. 9 und in einem Monat ca. 10-11 betragen. 
Unsinnig ist die Grafik natürlich trotzdem. Sie müsste entweder die initial gemeldeten Werte, die dann deutlich zu niedrig, aber immerhin vergleichbar wären oder adjustierte Werte erhalten. So wie es jetzt ist, sind die Werte deutlich niedriger als die Realität, jeden Tag anders, nicht vergleichbar und werden immer den Eindruck vermitteln, dass die Tendenz fallend ist. Das liegt aber nicht am RKI, denn Meldungen gemäß IfSG haben andere Zwecke als Hospitalisierungen unverzögert anzugeben.

**Comment by Kexplx** [comment]
Thanks for the clarification @pitrade 

Closed.

**Comment by HannesWuensche** [comment]
Hallo @pitrade,

vielen Dank für die korrekte Erklärung. 
Die Anregung zur Darstellung im Trendbericht gebe ich weiter. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
