### ISSUE TITLE
heute (2024-12-03) plötzliche Verringerung ALLER "fixierten" Werte rückwirkend um "-0,04" ??

### ISSUE THREAD

**Issue by Anna-Lyst** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#48]
Wie mir heute (03.12.) auffällt, sind seit heute (Mittag?) plötzlich in diesem(!) Repository *ALLE* eigentlich "fixierten" 7T-Hospitalisierungs-Inzidenzwerte rückwirkend für die letzten Wochen (gerade kontrolliert für die letzen mehr als fünf Wochen) um jeweils den Wert "-0,04" **vermindert** worden ???

Mehr Details:
* während zeitgleich das parallele Repository "Aktuell_Deutschland_COVID-19-Hospitalisierungen" für heute (noch) einen Hospitalisierungswert für alle AGs 00+ von "2.60" ausweist / gestern 02.12. Wert "3.30"
werden im Repo "Aktuell_Deutschland_adjustierte-COVID-19-Hospitalisierungen" die "fixierten" Werte seit heute Nachmittag mit "2.56" (03.12.) bzw. "3.00" (02.12) ausgewiesen.
* Die Gesamt-Bevölkerungszahl lautete bis einschließlich gestern "83.237.124" (und steht so auch heute noch im Repo "COVID-19-Faelle_7-Tage-Inzidenz_Deutschland";
doch in diesem Repo hier "Aktuell_Deutschland_adjustierte-COVID-19-Hospitalisierungen" lautet sie seit heute plötzlich "84.358.845" !!  (Zur besseren humanen Lesbarkeit mit Tausender-Punkt)

Könnte die Ursache für die heutige **umfassende Wert-Verminderung** etwa in einer _falschen_ Datengrundlage (nämlich Gesamt-Bevölkerungszahl D) in diesem einzelnen Repo liegen ???

Eine _zeitnahe_ Abklärung der Ursache - und gerne die Aufklärung von 'uns' allen, die (noch) mit diesen Werten weiterhin arbeiten - wäre sehr nett.

**Vielen Dank schon jetzt!**

**Comment by SimonScholler** [comment]
Liebe @Anna-Lyst,

die Änderungen kommen - wie von dir ja schon erörtert - dadurch zustande, dass die verwendeten Bevölkerungszahlen zur Bestimmung der adj. COVID-19 Hospitalisierungsinzidenz angepasst wurden. 
Dies passiert manchmal, um die Schätzungen noch etwas genauer zu machen. Bisher wurden nur Zahlen für das Jahr 2020 verwendet, nun werden die aktuellen Werte für die Jahre 2021 und 2022 verwendet. Für 2023 und 2024 werden nun die Zahlen von 2022 verwendet. Sobald die Werte für das Jahr 2023 vorliegen, werden diese auch verwendet werden. Dadurch kann es - wie akuell, aber auch in der Zukunft - vorkommen, dass sich Schätzungen retrospektiv verändern. Ist also kein Bug, sondern ein Feature und macht die Schätzung genauer.
Wir werden eine entsprechende Textpassage in der Dokumentation hinzufügen, um dies nochmal transparenter zu machen.

Nochmal danke für den Hinweis und herzliche Grüße,
Simon | RKI Open Data Team

**Comment by SimonScholler** [comment]
Liebe @Anna-Lyst,

ich denke es gibt hier unterschiedliche Auffassungen, was den Sachverhalt betrifft. 

zu a): Die Änderung ist insofern nicht tiefgreifend, als sie schlicht in einer Umrechnung mit etwas aktualisierten Bevölkerungsdaten entspricht, die auch über das Einsetzen der vorher verwendeten Bevölkerungsdaten wieder zu den früheren Ergebnissen umgerechnet werden können. Da die Bevölkerungszahlen transparent in den Daten stehen, ist dies leicht nachvollziehbar. Was das Wording 'fixiert' angeht, so bezieht sich die Inzidenz auf die Variable 'fixierte_7T _Hospitalisierung_Faelle', in denen die Fälle tatsächlich fixiert/unverändert bleiben. Da sich unser Wissen über die Bevölkerungszahlen jedoch ändern/verbessern kann, kann sich dadurch die angegebene Inzidenz verändern.

zu b): Generell bieten wir verschiedene Datensätze an, die erstmal unabhängig voneinander existieren. Wir sehen jedoch den Punkt, dass hier eine Harmonisierung sinnvoll ist und haben die Bevölkerungszahlen der 7-Tag-Inzidenzen nun auch dementsprechend angepasst. Danke hier für den Hinweis.

Generell finde ich den Ton nicht sehr zielführend und ich würde mir hier für die Zukunft eine etwas unaufgeregtere Kommunikation wünschen. 

Vielen Dank schon mal und schöne Grüße
Simon | RKI Open Data Team
