### ISSUE TITLE
Impfstatus der Hospitalisierten mit angeben

### ISSUE THREAD

**Issue by volviq** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#6]
Ist es möglich den Impfstatus der Hospitalisierten mit abzubilden? 

Wichtige Kategorien:
* ungeimpft, bzw unvollständig
* Voll geimpft (inkl. ausreichende Zeit für Immunaufbau)

Die Daten dazu scheinen ihrem Institut vorzuliegen:
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Inzidenz_Impfstatus.html

Mögliche weitere Kategorien, je nach vorhandener Datenbasis: 
* Erstimpfung
* Zweitimpfung, nicht vollendeter Schutz
* Drittimpfung erhalten
* Zweitimpfung länger als 4 Monate (oder 5/6, oder einfach: Monate nach Zweitimpfung)

**Comment by HannesWuensche** [comment]
Hallo @volviq,

vielen Dank für die Anregung. 
Wir sind in interner Abstimmung zu dem Thema und versuchen zeitnah weitere Informationen bereitzustellen. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data

**Comment by ASparwasser** [comment]
Guten Tag, 
genau diese Information würde in folgenden Diagrammen des [Dashboards ](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/COVID-19-Trends/COVID-19-Trends.html?__blob=publicationFile#/home) sehr interessante Informationen liefern:

- 7-Tage-Inzidenz
- COVID-19 auf Intensivstation
- 7-Tage-Inzidenz Hospitalisierungen
- Todesfälle

Vielen Dank für eure Arbeit.

**Comment by 8me** [comment]
Status?
