### ISSUE TITLE
Installation Widget ios (per Scriptable)

### ISSUE THREAD

**Issue by Augustus88** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#7]
Hallo, 
wie kann ich mit der App Scriptable die Hospitalisierungen bzw. die Adjustierte COVID-19-Hospitalisierungen als entsprechendes Widget auf meinem iPhone unter iOS 15 installieren bzw. welchen Code muss ich nehmen?
Sofern ich per Scriptable ein neues Widget auf meinem Homescreen erstelle, kommt bislang stets eine Fehlermeldung (z.b. „parse error“).
Wie kann ich das Problem lösen?

Vielen Dank im Voraus!

**Comment by HannesWuensche** [comment]
Hallo @Augustus88,

die App Scriptable wir nicht von uns betreut. 
Wir können daher bei dem Problem nicht weiterhelfen. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
