### ISSUE TITLE
Wert "NA" im CSV der Tagesdaten

### ISSUE THREAD

**Issue by rgerhards** [robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland#8]
Im CSV finden sich Zeilen wie diese
```
2020-03-01,Bundesgebiet,00,00+,NA,NA
```
Das stammt aus dem Datensatz vom 27.11. im Hauptverzeichnis.

Kann man "NA" als 0 werten? Sollte es bei Erstellung des CSV Sets dann nicht auch entsprechend korrigiert werden?

**Comment by HannesWuensche** [comment]
Hallo @rgerhards, 

vielen Dank für den Hinweis. 
Die angesprochene Ausprägung `NA` entsteht, wenn auf Deutschland Ebene an einem Tag keine Hospitalisierungen auftreten. Insofern ist die Annahme richtig, dass `NA` als `0` gewertet werden kann. Wir werden unsere Datenaufbereitung entsprechend anpassen so das die Ausprägung `NA` nicht mehr auftritt. 

Mit besten Grüßen
@HannesWuensche
für das Team RKI | Open Data
